version: '3'

networks:
  forgejo:
    driver: bridge

services:
  server:
    image: codeberg.org/forgejo/forgejo:1.20
    container_name: forgejo
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    networks:
        - forgejo
    volumes:
      - ./data/forgejo:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_ID=1000
      - USER_GID=1000
      - FORGEJO__database__DB_TYPE=postgres
      - FORGEJO__database__HOST=db:5432
      - FORGEJO__database__NAME=forgejo
      - FORGEJO__database__USER=forgejo
      - FORGEJO__database__PASSWD=forgejo
      - FORGEJO__webhook__ALLOWED_HOST_LIST=*
    depends_on:
        - db

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=forgejo
      - POSTGRES_PASSWORD=forgejo
      - POSTGRES_DB=forgejo
    networks:
      - forgejo
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
